server:
  port: 7002

spring:
  dubbo:
    server: true
    application:
      name: server-user #服务器名称
      id: demo-dubbo-user
    registry:
      protocol: zookeeper
      address: @zookeeper.address@
    protocol:
      name: dubbo
      port: 20882