server:
  port: 7004

spring:
  dubbo:
    server: true
    application:
      name: server-car #服务器名称
      id: demo-dubbo-car
    registry:
      protocol: zookeeper
      address: @zookeeper.address@
    protocol:
      name: dubbo
      port: 20884