server:
  port: 7003

spring:
  dubbo:
    server: true
    application:
      name: server-product #服务器名称
      id: demo-dubbo-product
    registry:
      protocol: zookeeper
      address: @zookeeper.address@
    protocol:
      name: dubbo
      port: 20883