server:
  port: 7001

spring:
  dubbo:
    server: true
    application:
      name: server-order #服务器名称
      id: demo-dubbo-order
    registry:
      protocol: zookeeper
      address: @zookeeper.address@
    protocol:
      name: dubbo
      port: 20881